app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path:      /
    defaults:  { _controller: AppBundle:Tournament:list }

signup:
    path:      /signup
    defaults:  { _controller: UserBundle:User:newUser }

login:
    path: /login
    defaults: { _controller: UserBundle:Security:login }

logout:
    path: /logout

user_edit:
    path: /user/{userId}/edit
    defaults: {_controller: UserBundle:User:editUser}

user_list:
    path: /admin/users
    defaults: {_controller: UserBundle:User:listUser}

tournament_list:
    path:      /tournament/list
    defaults:  { _controller: AppBundle:Tournament:list }

create_tournament:
    path:      /admin/tournament/create
    defaults:  { _controller: AppBundle:Tournament:create }

edit_tournament:
    path:      /admin/tournament/{tournamentId}/edit
    defaults:  { _controller: AppBundle:Tournament:edit }

delete_tournament:
    path:      /admin/tournament/{tournamentId}/delete
    defaults:  { _controller: AppBundle:Tournament:delete }

validate_tournament:
    path:      /admin/tournament/{tournamentId}/validate
    defaults:  { _controller: AppBundle:Tournament:validate }

tournament_validation_status:
    path:      /admin/tournament/{tournamentId}/validationstatus
    defaults:  { _controller: AppBundle:Tournament:validationstatus }

program_tournament:
    path: admin/tournament/{tournamentId}/program
    defaults: { _controller: AppBundle:Tournament:program }

program_tournament_matches:
    path: admin/tournament/{tournamentId}/programMatches
    defaults: { _controller: AppBundle:Tournament:programMatches }

program_tournament_rounds:
    path: admin/tournament/{tournamentId}/programRounds
    defaults: { _controller: AppBundle:Tournament:programRounds }

edit_day:
    path:      /admin/day/{dayId}/edit
    defaults:  { _controller: AppBundle:Day:edit }


add_teams:
    path:      /admin/tournament/{tournamentId}/teams
    defaults:  { _controller: AppBundle:Tournament:addTeams }

add_fields:
    path:      /admin/tournament/{tournamentId}/fields
    defaults:  { _controller: AppBundle:Tournament:addFields }

add_day:
    path:      /admin/tournament/{tournamentId}/day
    defaults:  { _controller: AppBundle:Tournament:addDay }

day_rounds_selector:
    path:      /admin/day/{dayId}/roundsSelector
    defaults:  { _controller: AppBundle:Day:roundsSelector }

edit_team:
    path:      /admin/team/{teamId}/edit
    defaults:  { _controller: AppBundle:Team:edit }


view_match:
    path:      /match/{matchId}
    defaults:  { _controller: AppBundle:Match:view }

edit_match:
    path:      /admin/match/{matchId}/edit
    defaults:  { _controller: AppBundle:Match:edit }


