app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path:      /
    defaults:  { _controller: AppBundle:Tournament:list }

signup:
    path:      /signup
    defaults:  { _controller: UserBundle:User:newUser }

login:
    path: /login
    defaults: { _controller: UserBundle:Security:login }

logout:
    path: /logout

user_edit:
    path: /user/{userId}/edit
    defaults: {_controller: UserBundle:User:editUser}

create_tournament:
    path:      /admin/createTournament
    defaults:  { _controller: AppBundle:Tournament:create }

edit_tournament:
    path:      /admin/editTournament/{tournamentId}
    defaults:  { _controller: AppBundle:Tournament:edit }

add_teams:
    path:      /admin/addTeams/{tournamentId}
    defaults:  { _controller: AppBundle:Tournament:addTeams }

edit_team:
    path:      /admin/editTeam/{teamId}
    defaults:  { _controller: AppBundle:Team:edit, teamId: null }

organize_pools:
    path:      /admin/organizePools/{tournamentId}
    defaults:  { _controller: AppBundle:Tournament:organizePools }

#---------- Player ----------

list_player:
    path:      /player/
    defaults:  { _controller: AppBundle:Default:debug }

get_player:
    path:      /player/{id}
    defaults:  { _controller: AppBundle:Default:debug }

create_player:
    path:      /player/create
    defaults:  { _controller: AppBundle:Default:debug }

update_player:
    path:      /player/{id}/update
    defaults:  { _controller: AppBundle:Default:debug }

delete_player:
    path:      /player/{id}/delete
    defaults:  { _controller: AppBundle:Default:debug }



#---------- Team ----------

list_team:
    path:      /team/
    defaults:  { _controller: AppBundle:Default:debug }

get_team:
    path:      /team/{id}
    defaults:  { _controller: AppBundle:Default:debug }

create_team:
    path:      /team/create
    defaults:  { _controller: AppBundle:Default:debug }

update_team:
    path:      /team/{id}/update
    defaults:  { _controller: AppBundle:Default:debug }

delete_team:
    path:      /team/{id}/delete
    defaults:  { _controller: AppBundle:Default:debug }


#---------- Pool ----------

list_pool:
    path:      /pool/
    defaults:  { _controller: AppBundle:Default:debug }

get_pool:
    path:      /pool/{id}
    defaults:  { _controller: AppBundle:Default:debug }

create_pool:
    path:      /pool/create
    defaults:  { _controller: AppBundle:Default:debug }

update_pool:
    path:      /pool/{id}/update
    defaults:  { _controller: AppBundle:Default:debug }

delete_pool:
    path:      /pool/{id}/delete
    defaults:  { _controller: AppBundle:Default:debug }


