app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path:      /
    defaults:  { _controller: AppBundle:Tournament:list }

signup:
    path:      /signup
    defaults:  { _controller: UserBundle:User:new }

login:
    path: /login
    defaults: { _controller: UserBundle:Security:login }

logout:
    path: /logout

user_edit:
    path: /user/{userId}/edit
    defaults: {_controller: UserBundle:User:edit}

user_list:
    path: /admin/users
    defaults: {_controller: UserBundle:User:list}

user_change_role:
    path: /admin/user/{userId}/changeRole
    defaults: {_controller: UserBundle:User:changeRole}

referee_match_list:
    path: /referee/{userId}/matchs
    defaults: {_controller: UserBundle:User:refereeMatchList}

tournament_list:
    path:      /tournament/list
    defaults:  { _controller: AppBundle:Tournament:list }

view_tournament:
    path:      /tournament/{tournamentId}
    defaults:  { _controller: AppBundle:Tournament:view }

create_tournament:
    path:      /admin/tournament/create
    defaults:  { _controller: AppBundle:Tournament:create }

edit_tournament:
    path:      /admin/tournament/{tournamentId}/edit
    defaults:  { _controller: AppBundle:Tournament:edit }

delete_tournament:
    path:       /admin/tournament/{tournamentId}/delete
    defaults:   { _controller: AppBundle:Tournament:delete }

validate_tournament:
    path:       /admin/tournament/{tournamentId}/validate
    defaults:   { _controller: AppBundle:Tournament:validate }

tournament_validation_status:
    path:       /admin/tournament/{tournamentId}/validationstatus
    defaults:   { _controller: AppBundle:Tournament:validationstatus }

program_tournament:
    path:       /admin/tournament/{tournamentId}/program
    defaults:   { _controller: AppBundle:Tournament:program }

tournament_validate_pools:
    path:       /admin/tournament/{tournamentId}/validatePools
    defaults:   { _controller: AppBundle:Tournament:validatePools }

program_tournament_matches:
    path:       /admin/tournament/{tournamentId}/programMatches
    defaults:   { _controller: AppBundle:Tournament:programMatches }

program_tournament_rounds:
    path:       /admin/tournament/{tournamentId}/programRounds
    defaults:   { _controller: AppBundle:Tournament:programRounds }

edit_day:
    path:      /admin/day/{dayId}/edit
    defaults:  { _controller: AppBundle:Day:edit }

add_teams:
    path:      /admin/tournament/{tournamentId}/teams
    defaults:  { _controller: AppBundle:Tournament:addTeams }

add_fields:
    path:      /admin/tournament/{tournamentId}/fields
    defaults:  { _controller: AppBundle:Tournament:addFields }

add_day:
    path:      /admin/tournament/{tournamentId}/day
    defaults:  { _controller: AppBundle:Tournament:addDay }

day_rounds_selector:
    path:      /admin/day/{dayId}/roundsSelector
    defaults:  { _controller: AppBundle:Day:roundsSelector }

edit_team:
    path:      /admin/team/{teamId}/edit
    defaults:  { _controller: AppBundle:Team:edit }

view_team:
    path:      /team/{teamId}
    defaults:  { _controller: AppBundle:Team:view }

view_match:
    path:      /match/{matchId}
    defaults:  { _controller: AppBundle:Match:view }

edit_match:
    path:      /admin/match/{matchId}/edit
    defaults:  { _controller: AppBundle:Match:edit }

print_match:
    path:      /match/{matchId}/print
    defaults:  { _controller: AppBundle:Match:print }

#------------ ROUTES API ------------

api_match_add_goal:
    path:       /api/match/{matchId}/addGoal/{teamId}
    defaults:  { _controller: AppBundle:Match:addGoal }

api_match_remove_goal:
    path:       /api/match/{matchId}/removeGoal/{teamId}
    defaults:  { _controller: AppBundle:Match:removeGoal }

api_match_add_card:
    path:       /api/match/{matchId}/addCard/{color}/{teamId}
    defaults:  { _controller: AppBundle:Match:addCard }

api_match_remove_card:
    path:       /api/match/{matchId}/removeCard/{color}/{teamId}
    defaults:  { _controller: AppBundle:Match:removeCard }

api_match_end:
    path:       /api/match/{matchId}/end
    defaults:  { _controller: AppBundle:Match:end }


