app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path:      /
    defaults:  { _controller: AppBundle:Tournament:list }

signup:
    path:      /signup
    defaults:  { _controller: UserBundle:User:newUser }

login:
    path: /login
    defaults: { _controller: UserBundle:Security:login }

logout:
    path: /logout

user_edit:
    path: /user/{userId}/edit
    defaults: {_controller: UserBundle:User:editUser}

user_list:
    path: /admin/users
    defaults: {_controller: UserBundle:User:listUser}

create_tournament:
    path:      /admin/createTournament
    defaults:  { _controller: AppBundle:Tournament:create }

edit_tournament:
    path:      /admin/editTournament/{tournamentId}
    defaults:  { _controller: AppBundle:Tournament:edit }

add_teams:
    path:      /admin/addTeams/{tournamentId}
    defaults:  { _controller: AppBundle:Tournament:addTeams }

edit_team:
    path:      /admin/editTeam/{teamId}
    defaults:  { _controller: AppBundle:Team:edit, teamId: null }

organize_pools:
    path:      /admin/organizePools/{tournamentId}
    defaults:  { _controller: AppBundle:Tournament:organizePools }

view_match:
    path:      /match/{matchId}
    defaults:  { _controller: AppBundle:Match:view }



