app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path:      /
    defaults:  { _controller: AppBundle:Tournament:list }

signup:
    path:      /signup
    defaults:  { _controller: UserBundle:User:newUser }

login:
    path: /login
    defaults: { _controller: UserBundle:Security:login }

logout:
    path: /logout

user_edit:
    path: /user/{userId}/edit
    defaults: {_controller: UserBundle:User:editUser}

user_list:
    path: /admin/users
    defaults: {_controller: UserBundle:User:listUser}

create_tournament:
    path:      /admin/tournament/create
    defaults:  { _controller: AppBundle:Tournament:create }

edit_tournament:
    path:      /admin/tournament/{tournamentId}/edit
    defaults:  { _controller: AppBundle:Tournament:edit }

add_teams:
    path:      /admin/tournament/{tournamentId}/teams
    defaults:  { _controller: AppBundle:Tournament:addTeams }

add_fields:
    path:      /admin/tournament/{tournamentId}/fields
    defaults:  { _controller: AppBundle:Tournament:addFields }

edit_team:
    path:      /admin/team/{teamId}/edit
    defaults:  { _controller: AppBundle:Team:edit }

validate_tournament:
    path:      /admin/tournament/{tournamentId}/validate
    defaults:  { _controller: AppBundle:Tournament:validate }

view_match:
    path:      /match/{matchId}
    defaults:  { _controller: AppBundle:Match:view }



